# Generated by Django 3.1.3 on 2020-11-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_auto_20201119_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like_users',
        ),
    ]
