# Generated by Django 3.1.3 on 2020-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_movie',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
