# Generated by Django 3.1.3 on 2020-11-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_searchmovie'),
        ('Accounts', '0003_auto_20201121_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wish_movie',
        ),
        migrations.AddField(
            model_name='user',
            name='wish_movie',
            field=models.ManyToManyField(related_name='liked_user', to='movies.Movie'),
        ),
    ]
