# Generated by Django 3.1.3 on 2020-11-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_liked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='liked_user',
        ),
    ]
