# Generated by Django 3.1.3 on 2020-11-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_liked_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
