# Generated by Django 3.1.3 on 2020-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_searchmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmovie',
            name='actor',
            field=models.CharField(default='kim', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmovie',
            name='director',
            field=models.CharField(default=2020, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmovie',
            name='image',
            field=models.CharField(default=2020, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmovie',
            name='link',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmovie',
            name='pubDate',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmovie',
            name='subtitle',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmovie',
            name='title',
            field=models.CharField(default='para', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmovie',
            name='userRating',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
    ]
