# Generated by Django 3.1.3 on 2020-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201122_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmovie',
            name='pubDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchmovie',
            name='userRating',
            field=models.CharField(max_length=50),
        ),
    ]
