# Generated by Django 3.1.3 on 2020-11-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20201122_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchMovie',
        ),
    ]
